name: Deploy on Azure App Service

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  prepare-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_GITHUB_SP_CREDENTIALS }}

      - name: Fetch Secrets and Create .env File
        run: |
          echo "" > .env.production
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env.production
          echo WEBSITE_HOSTNAME=${{secrets.WEBSITE_HOSTNAME}} >> .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            --secret id=env,src=.env.production \
            --tag ${{ secrets.ACR_LOGIN_SERVER }}/realtime-console:${{ github.sha }} \
            .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/realtime-console:${{ github.sha }}

  deploy:
    needs: prepare-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_GITHUB_SP_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "console-realtime"
          # publish-profile: ${{secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
          images: "${{ secrets.ACR_LOGIN_SERVER }}/realtime-console:${{ github.sha }}"

  cleanup:
    if: always()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Delete .env file
        run: rm -f .env.production
